// Generated by apps/promo/scripts/brand.ts from apps/promo/src/brand/logo.ts. Do not edit.

export const lockup = {
  viewBox: '0 -1.5 235.63 89',
  mark: 'translate(-28.5 -11)',
  word: 'translate(81.5 0)',
  weight: 11,
  signal: '#38BDF8',
  slashes: ['M41 74 L55.95 28', 'M61 74 L75.95 28'],
  bar: 'M36 91 L84 91',
  letters: [
    'M20 10 L20 68 Q20 80 32 80',
    'M9 30 L34 30',
    'M52 30 L68.25 80 L84.82 30 L101.06 80 L117.63 30',
    'M134.63 6 L134.63 68 Q134.63 80 146.63 80',
  ],
} as const
