import { Geist, Geist_Mono } from 'next/font/google'
import { cn } from 'twl'
import { Providers } from '~/providers'
import './styles/index.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  metadataBase: new URL('https://starter-next-app-two.vercel.app/'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    title: 'Starter Next App',
  },
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '96x96',
      url: '/favicon-96x96.png',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      url: '/favicon.svg',
    },
    {
      rel: 'shortcut icon',
      url: '/favicon.ico',
    },
    {
      rel: 'app-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
  openGraph: {
    title: 'Starter Next App',
    description: 'Generated by create next app',
    siteName: 'Starter Next App',
    images: [{ url: '/og.png' }],
  },
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// eslint-disable-next-line n/prefer-global/process
const isDev = process.env.NODE_ENV === 'development'

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
      className={cn(geistSans.variable, geistMono.variable)}
      suppressHydrationWarning
    >
      <head>
        {isDev && (
          <script
            src='https://unpkg.com/react-scan/dist/auto.global.js'
            defer
          />
        )}
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
